#!/usr/bin/env python3
"""
detector_feedback.py — 从检测器实测反馈反向更新指纹库

用法场景：用户跑过维普/知网 AIGC 检测，把标红的文字片段贴给我们，
脚本对比已有指纹库，找出"漏网"的高频模式，建议补充到 FINGERPRINTS。

输入格式（feedback.txt 每行一段标红文字）：
    随着信息技术的快速演进，云计算成为主流方案。
    本研究着重探究了上述问题在不同情境中的表现。
    通过深入剖析可以得出，该方法效果显著。
    ...

用法：
  # 1. 准备标红反馈文件（一行一段标红文字）
  # 2. 跑反馈分析
  python3 detector_feedback.py --feedback feedback.txt --top 20 --pretty

  # 3. 生成补丁直接 copy 到 score.py
  python3 detector_feedback.py --feedback feedback.txt --emit-patch
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

# 复用 score.py 的指纹库（动态导入）
sys.path.insert(0, str(Path(__file__).parent))
try:
    import score as score_mod  # type: ignore
except ImportError as e:
    print(f"无法导入 score.py: {e}", file=sys.stderr)
    sys.exit(2)


CN_RUN_RE = re.compile(r"[一-鿿]+")


def already_covered(ngram: str) -> bool:
    """判断某 n-gram 是否已被现有指纹库覆盖。"""
    for pattern, _, _ in score_mod.FINGERPRINTS:
        try:
            if re.search(pattern, ngram):
                return True
        except re.error:
            continue
    # 抽象后缀也算覆盖
    if any(s in ngram for s in score_mod.ABSTRACT_SUFFIX_HUA):
        return True
    if any(s in ngram for s in score_mod.ABSTRACT_SUFFIX_XING):
        return True
    return False


def extract_candidate_ngrams(text: str, n_min: int = 3, n_max: int = 8) -> list[str]:
    """提取候选 n-gram（连续中文片段，长度 3-8）。"""
    runs = CN_RUN_RE.findall(text)
    out = []
    for run in runs:
        for n in range(n_min, n_max + 1):
            for i in range(len(run) - n + 1):
                out.append(run[i:i + n])
    return out


def analyze_feedback(feedback_lines: list[str], top_k: int = 30,
                     min_count: int = 2, n_min: int = 3, n_max: int = 8) -> dict:
    """
    分析逻辑：
    1. 对每段标红文字提取候选 n-gram
    2. 统计跨段出现次数（同一 n-gram 在 ≥ min_count 段中出现才视为信号）
    3. 过滤已被现有指纹库覆盖的 n-gram
    4. 按"出现段数 × 长度"排序，长且高频的优先
    """
    # 段级出现：每个 n-gram 出现在多少段（不是总次数）
    segment_appearances: Counter = Counter()
    total_segments = 0
    coverage_stats = {"covered_by_existing": 0, "passed_through": 0}

    for line in feedback_lines:
        line = line.strip()
        if not line:
            continue
        total_segments += 1
        # 段内 n-gram 去重，避免一个段重复贡献
        seen_in_segment = set(extract_candidate_ngrams(line, n_min, n_max))
        # 检查现有指纹覆盖度（用于报告）
        existing_covered = sum(1 for pat, _, _ in score_mod.FINGERPRINTS
                               if re.search(pat, line))
        if existing_covered > 0:
            coverage_stats["covered_by_existing"] += 1
        else:
            coverage_stats["passed_through"] += 1
        for ng in seen_in_segment:
            segment_appearances[ng] += 1

    # 找漏网：跨多段出现，且未被现有库覆盖
    candidates = []
    for ng, segs in segment_appearances.items():
        if segs < min_count:
            continue
        if already_covered(ng):
            continue
        # 排除常见无意义短词（停用词）
        if len(ng) <= 2 and ng in {"研究", "方法", "分析", "提出", "本文", "结果",
                                    "实验", "数据", "模型", "效果"}:
            continue
        candidates.append({
            "ngram": ng,
            "len": len(ng),
            "segments_appeared_in": segs,
            "coverage_ratio": round(segs / max(total_segments, 1), 2),
            "score": segs * len(ng),  # 段数 × 长度
        })

    # 去除被更长候选完全包含的子串（保留最长且高分的）
    candidates.sort(key=lambda x: (-x["score"], -x["len"]))
    final = []
    seen_super: set[str] = set()
    for c in candidates:
        # 如果当前 n-gram 是已选某条的子串且分数没显著更高，跳过
        is_substring = any(c["ngram"] in s and c["ngram"] != s for s in seen_super)
        if is_substring:
            continue
        final.append(c)
        seen_super.add(c["ngram"])
        if len(final) >= top_k:
            break

    return {
        "metadata": {
            "total_feedback_segments": total_segments,
            "covered_by_existing_dict": coverage_stats["covered_by_existing"],
            "passed_through_existing_dict": coverage_stats["passed_through"],
            "current_dict_recall": round(
                coverage_stats["covered_by_existing"] / max(total_segments, 1), 2),
            "n_gram_range": [n_min, n_max],
            "min_count_threshold": min_count,
        },
        "missed_patterns": final,
    }


def assign_significance(segs: int, total: int, length: int) -> str:
    """根据出现频率和长度推断显著度。"""
    coverage = segs / max(total, 1)
    if coverage >= 0.5 and length >= 4:
        return "S+"
    if coverage >= 0.3:
        return "S"
    if coverage >= 0.15 or length >= 6:
        return "A"
    return "B"


def emit_patch(result: dict) -> str:
    lines = ["# === Auto-generated by detector_feedback.py ===",
             f"# 来源：检测器实测反馈分析（共 {result['metadata']['total_feedback_segments']} 段标红）",
             f"# 现有词典召回率：{result['metadata']['current_dict_recall']*100:.0f}%",
             "# 注意：人工 review 后再合并；以下是漏网模式建议。",
             ""]
    total = result["metadata"]["total_feedback_segments"]
    for c in result["missed_patterns"]:
        sig = assign_significance(c["segments_appeared_in"], total, c["len"])
        ngram_escaped = re.escape(c["ngram"])
        lines.append(
            f'    (r"{ngram_escaped}", "{sig}", "反馈词"),  '
            f'# 出现于 {c["segments_appeared_in"]}/{total} 段, len={c["len"]}'
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="从检测器反馈反向更新指纹库")
    p.add_argument("--feedback", type=Path, required=True,
                   help="标红文字反馈文件（每行一段）")
    p.add_argument("--top", type=int, default=30)
    p.add_argument("--min-count", type=int, default=2,
                   help="最小段数阈值（一个 n-gram 至少出现在 N 段中才算信号）")
    p.add_argument("--n-min", type=int, default=3)
    p.add_argument("--n-max", type=int, default=8)
    p.add_argument("--emit-patch", action="store_true")
    p.add_argument("--pretty", action="store_true")
    args = p.parse_args(argv)

    if not args.feedback.exists():
        print(f"找不到反馈文件: {args.feedback}", file=sys.stderr)
        return 2

    lines = args.feedback.read_text(encoding="utf-8").splitlines()
    result = analyze_feedback(lines, top_k=args.top, min_count=args.min_count,
                              n_min=args.n_min, n_max=args.n_max)

    if args.emit_patch:
        print(emit_patch(result))
        return 0

    indent = 2 if args.pretty else None
    print(json.dumps(result, ensure_ascii=False, indent=indent))
    return 0


if __name__ == "__main__":
    sys.exit(main())
