#!/usr/bin/env python3
"""
train_dict.py — 用真实语料做 χ² 显著度训练

把"经验近似"的指纹库升级为"语料驱动"的统计权重。
用户提供两个目录：
  human_corpus/  — 真实人类学术论文（CNKI 硕博 / 期刊正文）
  ai_corpus/     — GPT/Claude/文心一言生成的同领域论文

脚本会：
1. 提取所有候选 n-gram（默认 2-gram 到 5-gram）
2. 对每个候选跑 χ² 独立性检验
3. 按 χ² 显著度排序，输出前 N 个候选
4. 自动建议加入 score.py 的 FINGERPRINTS 列表（按显著度分档）

零依赖（仅标准库 + math）。

用法：
  # 1. 准备语料（每个 .txt 一篇文章）
  ls human_corpus/  # paper_001.txt paper_002.txt ...
  ls ai_corpus/     # gpt_001.txt gpt_002.txt ...

  # 2. 训练
  python3 train_dict.py --human human_corpus --ai ai_corpus --output candidates.json

  # 3. 查看 top-50 候选
  python3 train_dict.py --human human_corpus --ai ai_corpus --top 50 --pretty

  # 4. 生成 FINGERPRINTS 补丁（直接 copy-paste 到 score.py）
  python3 train_dict.py --human human_corpus --ai ai_corpus --emit-patch
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
from collections import Counter
from pathlib import Path


CN_CHAR_RE = re.compile(r"[一-鿿]+")


def extract_ngrams(text: str, n_min: int = 2, n_max: int = 5) -> list[str]:
    """提取所有连续中文 n-gram。"""
    runs = CN_CHAR_RE.findall(text)
    ngrams = []
    for run in runs:
        for n in range(n_min, n_max + 1):
            for i in range(len(run) - n + 1):
                ngrams.append(run[i:i + n])
    return ngrams


def load_corpus(path: Path, n_min: int, n_max: int) -> tuple[Counter, int]:
    """读目录下所有 .txt 文件，返回 (Counter[ngram], 总 n-gram 数)"""
    counter: Counter = Counter()
    total = 0
    files = list(path.glob("**/*.txt")) + list(path.glob("**/*.md"))
    if not files:
        print(f"⚠️  {path} 下未找到 .txt/.md 文件", file=sys.stderr)
        return counter, 0
    for f in files:
        try:
            text = f.read_text(encoding="utf-8")
        except Exception as e:
            print(f"跳过 {f}: {e}", file=sys.stderr)
            continue
        ngs = extract_ngrams(text, n_min, n_max)
        counter.update(ngs)
        total += len(ngs)
    return counter, total


def chi_square(a: int, b: int, c: int, d: int) -> float:
    """
    2x2 列联表 χ² 检验:
       human  ai
    存在  a    b
    不存在 c   d
    """
    n = a + b + c + d
    if n == 0:
        return 0.0
    # 期望频数
    row1 = a + b
    row2 = c + d
    col1 = a + c
    col2 = b + d
    if row1 == 0 or row2 == 0 or col1 == 0 or col2 == 0:
        return 0.0
    e_a = row1 * col1 / n
    e_b = row1 * col2 / n
    e_c = row2 * col1 / n
    e_d = row2 * col2 / n

    def term(obs: int, exp: float) -> float:
        if exp == 0:
            return 0.0
        return (obs - exp) ** 2 / exp

    return term(a, e_a) + term(b, e_b) + term(c, e_c) + term(d, e_d)


def train(human: Counter, human_total: int, ai: Counter, ai_total: int,
          min_count: int = 5, top_k: int = 200) -> list[dict]:
    """
    训练：对每个 n-gram 算 χ²，返回按显著度排序的候选词。
    只保留 ai 频率显著高于 human 的（AI 偏好词）。
    """
    candidates = []
    all_ngrams = set(human) | set(ai)
    for ng in all_ngrams:
        h = human[ng]
        a = ai[ng]
        # 至少要在某一侧出现 min_count 次
        if max(h, a) < min_count:
            continue
        # 计算频率（每千 n-gram）
        h_freq = h / max(human_total, 1) * 1000
        a_freq = a / max(ai_total, 1) * 1000
        # 只关心 AI 偏好词（a_freq > h_freq）
        if a_freq <= h_freq:
            continue
        # χ² 检验
        chi2 = chi_square(h, a, human_total - h, ai_total - a)
        # 提升倍数
        ratio = a_freq / max(h_freq, 0.01)
        candidates.append({
            "ngram": ng,
            "len": len(ng),
            "human_count": h,
            "ai_count": a,
            "human_freq_per_1k": round(h_freq, 3),
            "ai_freq_per_1k": round(a_freq, 3),
            "chi_square": round(chi2, 2),
            "ratio_ai_to_human": round(ratio, 2),
        })

    candidates.sort(key=lambda x: x["chi_square"], reverse=True)
    return candidates[:top_k]


def assign_significance(chi2: float) -> str:
    """χ² → 显著度分档"""
    if chi2 >= 1000:
        return "S+"
    if chi2 >= 300:
        return "S"
    if chi2 >= 100:
        return "A"
    if chi2 >= 30:
        return "B"
    if chi2 >= 10:
        return "C"
    return "D"


def emit_patch(candidates: list[dict]) -> str:
    """生成可直接 copy-paste 到 score.py 的 FINGERPRINTS 补丁。"""
    lines = ["# === Auto-generated by train_dict.py ===",
             "# 来源：用户语料的 χ² 训练",
             "# 注意：人工 review 后再合并。重叠子串可能需要去重。",
             ""]
    for c in candidates:
        sig = assign_significance(c["chi_square"])
        # 转义正则特殊字符
        ngram_escaped = re.escape(c["ngram"])
        lines.append(
            f'    (r"{ngram_escaped}", "{sig}", "训练词"),  '
            f'# χ²={c["chi_square"]}, ai/human={c["ratio_ai_to_human"]}x'
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="χ² 训练指纹词典")
    p.add_argument("--human", type=Path, required=True,
                   help="人类语料目录（.txt/.md 文件）")
    p.add_argument("--ai", type=Path, required=True,
                   help="AI 生成语料目录")
    p.add_argument("--output", type=Path,
                   help="输出 JSON 路径（不指定则 stdout）")
    p.add_argument("--top", type=int, default=200, help="保留 top-K 显著候选")
    p.add_argument("--min-count", type=int, default=5,
                   help="最小出现次数阈值")
    p.add_argument("--n-min", type=int, default=2, help="最小 n-gram 长度")
    p.add_argument("--n-max", type=int, default=5, help="最大 n-gram 长度")
    p.add_argument("--emit-patch", action="store_true",
                   help="生成 score.py FINGERPRINTS 补丁文本")
    p.add_argument("--pretty", action="store_true")
    args = p.parse_args(argv)

    if not args.human.is_dir():
        print(f"--human 必须是目录: {args.human}", file=sys.stderr)
        return 2
    if not args.ai.is_dir():
        print(f"--ai 必须是目录: {args.ai}", file=sys.stderr)
        return 2

    print(f"加载人类语料 {args.human}...", file=sys.stderr)
    h_counter, h_total = load_corpus(args.human, args.n_min, args.n_max)
    print(f"  → {len(h_counter)} 唯一 n-gram, {h_total} 总数", file=sys.stderr)

    print(f"加载 AI 语料 {args.ai}...", file=sys.stderr)
    a_counter, a_total = load_corpus(args.ai, args.n_min, args.n_max)
    print(f"  → {len(a_counter)} 唯一 n-gram, {a_total} 总数", file=sys.stderr)

    if h_total == 0 or a_total == 0:
        print("两侧语料不能为空", file=sys.stderr)
        return 2

    print("训练中...", file=sys.stderr)
    candidates = train(h_counter, h_total, a_counter, a_total,
                       min_count=args.min_count, top_k=args.top)
    print(f"  → 得到 {len(candidates)} 个 AI 偏好候选词", file=sys.stderr)

    if args.emit_patch:
        print(emit_patch(candidates))
        return 0

    indent = 2 if args.pretty else None
    output_data = {
        "metadata": {
            "human_corpus_files": len(list(args.human.glob("**/*.txt"))) +
                                  len(list(args.human.glob("**/*.md"))),
            "ai_corpus_files": len(list(args.ai.glob("**/*.txt"))) +
                              len(list(args.ai.glob("**/*.md"))),
            "human_ngram_total": h_total,
            "ai_ngram_total": a_total,
            "n_min": args.n_min,
            "n_max": args.n_max,
            "min_count": args.min_count,
        },
        "candidates": candidates,
    }
    out = json.dumps(output_data, ensure_ascii=False, indent=indent)

    if args.output:
        args.output.write_text(out, encoding="utf-8")
        print(f"已写入 {args.output}", file=sys.stderr)
    else:
        print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
